### ISSUE TITLE
提示丢失mfc140.ud.dll

### ISSUE THREAD

**Issue by cuihua0** [zhangc47/TopWnd#1]
无法启动此程序，因为计算机中丢失mfc140ud.dll，尝试重新安装该程序以解决问题

**Comment by Zane47** [comment]
Maybe the following method will work for you:
https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_update-insiderplat_pc/mfc140uddll-missing/dc872428-c1e1-403e-9ea2-9c9e40efed86

Ps: the original dev platform of this project is VS2015.

Wish this may help you.
